import React, { ReactNode } from 'react'
import { Navbar } from '../Navbar'
import Head from 'next/head'

interface MainLayoutProps {
    children?: ReactNode;
}

export const MainLayout = ({ children }: MainLayoutProps) => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Head>
                {/* <title>Jean Reyes   </title> */}
                <meta name="description" content="Generated by create next app 2" />
            </Head>
            <Navbar/>
           { children }
        </>
    )
}
